common/models/TranslationForm.php
<?php
namespace common\models;
use dezmont765\yii2bundle\components\Alert;
use Yii;
use yii\base\Model;

/**
 * Created by PhpStorm.
 * User: DezMonT
 * Date: 16.04.2015
 * Time: 12:53
 */

class TranslationForm extends Model
{
    public $language;
    public $category;
    public $translation;
    public $source_message;

    public function rules()
    {
        return [
            ['category','default','value'=>'app'],
            [['language','category','translation','source_message'],'required'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'category' =>  Yii::t('app', ':translation_model_category'),
            'source_message' =>  Yii::t('app', ':translation_model_source_message'),
            'translation' =>  Yii::t('app', ':translation_model_translation'),
        ];
    }

    public function createMessage()
    {
        if(!$this->validate()){
            Alert::addError(Yii::t('app',':translation_error_translation_not_saved'),$this->errors);
            return false;
        }
        $sourceMessage = new SourceMessage();
        $sourceMessage->language = $this->language;
        $sourceMessage->category = $this->category;
        $sourceMessage->message = $this->source_message;
        $sourceMessage->messageTranslation = $this->translation;
        if(!$sourceMessage->save())
             Alert::addError(Yii::t('app',':translation_error_translation_not_saved'),$sourceMessage->errors);
        return false;
    }


}

backend/controllers/TranslationController.php
<?php
namespace backend\controllers;
use backend\filters\TranslationLayout;
use common\models\Message;
use common\models\SourceMessage;
use common\models\SourceMessageSearch;
use common\models\TranslationForm;
use common\models\TranslationLoad;
use backend\actions\TranslationEditableAction;
use dezmont765\yii2bundle\controllers\MainController;
use Yii;
use dezmont765\yii2bundle\components\Alert;

/**
 * Created by PhpStorm.
 * User: DezMonT
 * Date: 15.04.2015
 * Time: 14:30
 */

class TranslationController extends MainController
{
    public function behaviors()
    {
        return [
//            'access' => [
//                'class' => AccessControl::className(),
//            ]
            'layout' => ['class'=>TranslationLayout::className()]
        ];
    }

    public function actions()
    {
        return  [
            'ajax-update' => [
                'class' => TranslationEditableAction::className(),
                'modelClass' => SourceMessage::className(),
                'forceCreate' => false,
                'preProcess'=>function($model){
                    $model->language = Yii::$app->request->get('language');
                }
            ]
        ];
    }

    public function actionLoad()
    {
        $translationLoad = new TranslationLoad();
        $translationLoad->load(Yii::$app->request->post());
        $translationLoad->loadTranslation();
        return $this->redirect(['translation/import','language'=>$translationLoad->language]);
    }

    public function actionList()
    {
        $search = new SourceMessageSearch();
        $translationForm = new TranslationForm();

        $translationForm->language = Yii::$app->request->getQueryParam('language', Yii::$app->language);

        $search->load(Yii::$app->request->get());
        $search->language =  $translationForm->language;
        $data_provider = $search->search();
        return $this->render('translation-list',['data_provider'=>$data_provider,'search_model'=>$search,
                                                 'translationForm'=>$translationForm,
        ]);
    }

    public function actionCreate()
    {
        $create = new TranslationForm();
        $create->load(Yii::$app->request->post());
        $create->createMessage();
        return $this->redirect(['translation/list','language'=>$create->language]);
    }

    public function actionDelete($id,$language)
    {
        $model = $this->findModel(Message::className(),['id'=>$id,'language'=>$language]);
        if($model->delete())
        {
            Alert::addSuccess(Yii::t('messages','Translation has been successfully deleted'));

        }
        else
            Alert::addError(Yii::t('messages','Translation has not been deleted'));
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionMassDelete($id)
    {

    }

    public function actionImport()
    {
        $translationLoad = new TranslationLoad();
        $translationLoad->language = Yii::$app->request->getQueryParam('language', Yii::$app->language);
        return $this->render('translation-load',['model'=>$translationLoad]);
    }
}

backend/views/translation/translation-form.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */
\backend\assets\Select2Asset::register($this);
?>
<div class="translation-form">
<?php $form = ActiveForm::begin(['layout'=>'inline',
                                 'action'=>Url::to(['translation/create']),
                                 'fieldConfig' => [
                                     'template' => "<span class='left-mrg-10'>{input}\n{hint}\n{error}</span>",
                                     'inputTemplate' => '{input}',
                                 ],
                                ]); ?>
<?= $form->errorSummary($model);?>

<?= $form->field($model, 'source_message')->textInput(['placeholder'=>$model->getAttributeLabel('source_message'),'class'=>'translation-form-input form-control',]) ?>
<?= $form->field($model, 'translation')->textInput(['placeholder'=>$model->getAttributeLabel('translation'),'class'=>'translation-form-input form-control']) ?>
<?= $form->field($model, 'language')->hiddenInput(['style'=>'display:none']) ?>


    <?= Html::submitButton(Yii::t('app', '+') , ['class' =>  'btn btn-success']) ?>

<?php ActiveForm::end(); ?>
</div>

backend/views/translation/translation-list.php
<?php

use dosamigos\grid\EditableColumn;
use lajax\languagepicker\widgets\LanguagePicker;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel common\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Translations');
?>
<div class="translation-list">

    <span><?= Yii::t('app','translation_form_language')?>&nbsp;</span>
    <?= LanguagePicker::widget([
                                                                 'skin' => LanguagePicker::SKIN_DROPDOWN,
                                                                 'size' => LanguagePicker::SIZE_SMALL,
                                                                 'link' => function($language){
                                                                     return Url::to(['','language'=>$language]);
                                                                 },
                                                                 'active' => $translationForm->language,
                                                             ]); ?>
    </div>
    <?= $this->render('translation-form',['model'=>$translationForm]) ;?>
    <?= GridView::widget([
                             'dataProvider' => $data_provider,
                             'filterModel' => $search_model,
                             'columns' => [
                                 ['class' => 'yii\grid\SerialColumn'],
                                 [
                                         'class'=> EditableColumn::className(),
                                         'format'=>'raw',
                                         'attribute'=>'category',
                                         'url'=>['ajax-update','language'=>$translationForm->language],
                                 ],
                                 [
                                     'class'=> EditableColumn::className(),
                                     'attribute'=>'message',
                                     'format'=>'raw',
                                     'url'=>['ajax-update','language'=>$translationForm->language],
                                 ],

                                 [
                                     'class'=> EditableColumn::className(),
                                     'attribute'=>'messageTranslation',
                                     'format'=>'raw',
                                     'url'=>['ajax-update','language'=>$translationForm->language],
                                 ],
                                 ['class' => 'yii\grid\ActionColumn',
                                    'template' => '{delete}',
                                    'buttons' => [
                                        'delete' => function($url,$model,$key) use ($translationForm) {
                                            $url = Url::to(['translation/delete','id'=>$model->id,'language'=>$translationForm->language]);
                                            return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                                                'title' => Yii::t('yii', 'Delete'),
                                                'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                                                'data-method' => 'post',
                                                'data-pjax' => '0',
                                            ]);
                                        }
                                    ],
                                 ],
                             ],
                         ]); ?>

</div>

backend/views/translation/translation-load.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */
\backend\assets\Select2Asset::register($this);
?>
<br>
<?php $form = ActiveForm::begin([
                                 'action'=>Url::to(['translation/load']),

                                 'options' => [
                                     'enctype' => 'multipart/form-data'
                                 ]
                                ]); ?>
<?= $form->errorSummary($model);?>

<?= $form->field($model, 'file')->fileInput(['placeholder'=>$model->getAttributeLabel('file')]) ?>
<?= $form->field($model, 'isUpdate')->checkbox() ?>
<div class="hidden">
<?= $form->field($model, 'language')->hiddenInput(['style'=>'display:none']) ?>
</div>


    <?= Html::submitButton(Yii::t('translation_load', ":upload_translation_file") , ['class' =>  'btn btn-success']) ?>

<?php ActiveForm::end(); ?>
<br>