backend/models/User.php
<?php
/**
 * Created by PhpStorm.
 * User: DezMonT
 * Date: 25.03.2015
 * Time: 15:28
 */
namespace backend\models;
use console\controllers\RbacController;

class User extends \common\models\User
{
    public static function findIdentity($id)
    {
        $query = static::find();
        $query->andFilterWhere(['id'=>$id,'status'=>self::STATUS_ACTIVE]);
        $query->andFilterWhere(['not',['role'=>RbacController::user]]);
        return $query->one();
    }

    public static function findByEmail($email)
    {
        $query = static::find();
        $query->andFilterWhere(['email'=>$email,'status'=>self::STATUS_ACTIVE]);
        $query->andFilterWhere(['not',['role'=>RbacController::user]]);
        return $query->one();
    }
}

frontend/models/User.php
<?php
/**
 * Created by PhpStorm.
 * User: DezMonT
 * Date: 25.03.2015
 * Time: 15:28
 */
namespace frontend\models;
use console\controllers\RbacController;

class User extends \common\models\User
{
    public static function findIdentity($id)
    {
        $query = static::find();
        $query->andFilterWhere(['id'=>$id,'status'=>self::STATUS_ACTIVE,'role'=>RbacController::user]);
        return $query->one();
    }

    public static function findByEmail($email)
    {
        $query = static::find();
        $query->andFilterWhere(['email'=>$email,'status'=>self::STATUS_ACTIVE,'role'=>RbacController::user]);
        return $query->one();
    }
}

backend/controllers/UserController.php
<?php
namespace backend\controllers;

use backend\actions\UserEditableAction;
use backend\filters\UserLayout;
use common\models\User;
use common\models\UserSearch;
use console\controllers\RbacController;
use dezmont765\yii2bundle\actions\CreateAction;
use dezmont765\yii2bundle\actions\DeleteAction;
use dezmont765\yii2bundle\actions\ListAction;
use dezmont765\yii2bundle\actions\UpdateAction;
use dezmont765\yii2bundle\components\Alert;
use dezmont765\yii2bundle\controllers\MainController;
use Exception;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends MainController
{
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['list', 'create', 'availableGroups'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [RbacController::admin, RbacController::super_admin]
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'layout' => UserLayout::className()
        ];
    }


    public function actions() {
        return [
            'ajaxUpdate' => [
                'class' => UserEditableAction::className(),
                'modelClass' => User::className(),
                'forceCreate' => false
            ],
            'list' => [
                'class' => ListAction::className(),
                'model_class' => UserSearch::className()
            ],
            'create' => [
                'class' => CreateAction::className(),
                'permission' => RbacController::create_profile
            ],
            'update' => [
                'class' => UpdateAction::className(),
                'permission' => RbacController::update_profile
            ],
            'delete' => [
                'class' => DeleteAction::className(),
                'permission' => RbacController::delete_profile
            ]
        ];
    }


    public function getModelClass() {
        return User::className();
    }


    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $model = $this->findModel(User::className(), $id);
        self::checkAccess(RbacController::delete_profile, ['user' => $model]);
        $model->delete();
        return $this->redirect(['list']);
    }


    public function actionAvailableGroups() {
        /**@var User $user */
        $user = Yii::$app->user->identity;
        return json_encode($user->getEditableRoles());
    }


    public function actionMassDelete() {
        if(isset($_POST['keys'])) {
            foreach($_POST['keys'] as $key) {
                try {
                    $model = $this->findModel(User::className(), $key);
                    if($model) {
                        if($model->delete()) {
                            Alert::addSuccess("Items has been successfully deleted");
                        }
                    }
                }
                catch(Exception $e) {
                    Alert::addError('Item has not been deleted', $e->getMessage());
                }
            }
        }
        return $this->redirect(['list']);
    }


    public function actionAsAjax($id) {
        $model = $this->findModel(User::className(), $id);
        Yii::$app->response->format = Response::FORMAT_JSON;
        return $model->toArray();
    }


    /**
     * Provides json response for select2 plugin
     */
    public function actionGetSelectionList() {
        self::selectionList(User::className(), 'name');
    }


    /**
     * Provides json response for select2 plugin
     */
    public function actionGetSelectionById() {
        self::selectionById(User::className(), 'name');
    }
}

frontend/controllers/UserController.php
<?php
/**
 * Created by PhpStorm.
 * User: DezMonT
 * Date: 01.04.2015
 * Time: 18:58
 */
namespace frontend\controllers;

use common\models\User;
use common\models\UserImages;
use common\models\UserImagesSearch;
use console\controllers\RbacController;
use dezmont765\yii2bundle\components\Alert;
use dezmont765\yii2bundle\controllers\MainController;
use frontend\filters\UserLayout;
use Yii;
use yii\db\ActiveQuery;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;
use yii\web\ServerErrorHttpException;

class UserController extends MainController
{
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ],
            'layout' => UserLayout::className()
        ];
    }


    /**
     * Displays a single User model.
     * @return mixed
     */
    public function actionView() {
        $model = $this->findModel(User::className(), Yii::$app->user->id);
        self::checkAccess(RbacController::update_profile, ['model' => $model]);
        return $this->render('user-view', [
            'model' => $model,
        ]);
    }


    /**
     * @throws HttpException
     * check users by received code, and if everything is ok, marks them as verified
     */
    public function actionVerifyEmail() {
        $code = Yii::$app->request->getQueryParam('code');
        if($code) {
            $user = User::findOne(['email_verification_code' => $code]);
            if(!($user instanceof User)) {
                throw new NotFoundHttpException(Yii::t('messages', 'Invalid code'));
            }
            $user->email_verification_status = User::EMAIL_VERIFIED;
            if(!$user->save()) {
                throw new ServerErrorHttpException(Yii::t('messages',
                                                          'Something goes wrong. Please contact us, or try again later.'));
            }
            $user->sendWelcomeMail();
            return $this->goHome();
        }
        else {
            throw new BadRequestHttpException('Invalid code');
        }
    }


    public function actionGetVerificationMail() {
        /**@var User $user */
        $user = Yii::$app->user->identity;
        if($user->renewVerificationCode()) {
            $user->sendVerificationEmail($user->email_verification_code);
            return $this->redirect(['user/view', 'id' => $user->id]);
        }
        else {
            return $this->goHome();
        }
    }


    public function actionUploadPicture() {
        $model = User::getLogged(true);
        if($model->load(Yii::$app->request->post())) {
            $model->save();
        }
        return $this->render('upload-picture-form', ['model' => $model]);
    }


    public function actionPictures() {
        $model = new UserImagesSearch();
        $model->load(Yii::$app->request->queryParams);
        $dataProvider = $model->search(UserImages::find()->joinWith(['user' => function (ActiveQuery $query) {
            $query->andWhere(['user.id' => Yii::$app->user->id]);
        }]));
        return $this->render('pictures-list', ['dataProvider' => $dataProvider, 'searchModel' => $model]);
    }


    public function actionRotatePicture($id) {
        $user = User::getLogged(true);
        $user->rotateImage($id);
        return $this->redirect(['pictures']);
    }


    public function actionDeletePicture($id) {
        $user = User::getLogged(true);
        if($user->deleteFileByRelationId('picture', $id)) {
            Alert::addSuccess('Picture has been deleted');
        }
        return $this->redirect(['pictures']);
    }

}

frontend/views/user/pictures-list.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel common\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->title = Yii::t('user', 'List users');
?>
<div class="user-index">
    <br>
    <?= GridView::widget([
                             'id' => 'picture-list',
                             'dataProvider' => $dataProvider,
                             'filterModel' => $searchModel,
                             'columns' => [
                                 [
                                     'attribute' => 'name',
                                     'format' => 'raw',
                                     'value' => function (\common\models\UserImages $data) {
                                         return Html::img(\common\models\User::getLogged(true)
                                                                             ->getFileByRelationId($data->id, 'picture',
                                                                                                   false, true),
                                                          ['width' => 100]);
                                     }
                                 ],
                                 ['class' => 'yii\grid\ActionColumn',
                                  'template' => '{rotate}{delete}',
                                  'buttons' => [
                                      'rotate' => function ($url, $model, $key) {
                                          $url = Url::to(['user/rotate-picture', 'id' => $key]);
                                          return Html::a('<span class="glyphicon glyphicon-refresh"></span>', $url, [
                                              'title' => Yii::t('yii', 'Rotate'),
                                          ]);
                                      },
                                      'delete' => function ($url, $model, $key) {
                                          $url = Url::to(['user/delete-picture', 'id' => $key]);
                                          return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                                              'title' => Yii::t('yii', 'Delete'),
                                              'data-confirm' => 'Are you sure you want to delete this picture?',
                                              'data-method' => 'post',
                                              'data-pjax' => '0'
                                          ]);
                                      }
                                  ],
                                 ],
                             ],
                         ]); ?>

</div>

frontend/views/user/upload-picture-form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">
    <br>
    <?php $form = ActiveForm::begin([
                                        'id' => 'image-upload-form',
                                        'enableAjaxValidation' => false,
                                        'enableClientValidation' => true,
                                        'options' => ['enctype' => 'multipart/form-data']
                                    ]); ?>
    <?= $form->errorSummary($model); ?>

    <?= $form->field($model, 'picture[]')->fileInput(['multiple'=>true]); ?>


    <div class="form-group">
        <?= Html::submitButton('Upload picture',['class'=>'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/user/user-view.php
<?php

use common\models\User;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $user common\models\User */

$this->title = $model->email;
$user = Yii::$app->user->identity;
if($user->email_verification_status == User::EMAIL_NOT_VERIFIED):?>
    <br>
    <p>
        <?php echo Yii::t('message','You have not yet confirmed your email address. Please do so to ensure your account will remain active.')?>
        <a href="<?=Url::to('/user/get-verification-mail')?>"><?php echo Yii::t('messages','Click here to resend the confirmation email.')?></a>
    </p>
<?php endif?>
<div class="user-view">

    <br>


    <?= DetailView::widget([
                               'model' => $model,
                               'attributes' => [
                                   'id',
                                   'email:email',
                                   [
                                       'attribute'=>'status',
                                       'value'=>$model->getCurrentStatus()
                                   ],
                                   'created_at:datetime',
                                   'updated_at:datetime',
                                   [
                                       'attribute'=>'role',
                                       'value'=>$model->getCurrentRole()
                                   ],
                               ],
                           ]) ?>

</div>